article: https://developers.hardwario.com/projects/radio-soil-sensor
video: https://www.youtube.com/watch?v=6kU-_ldaGOw&feature=youtu.be
images:
  - title:
    url: https://raw.githubusercontent.com/hardwario/website/master/static/kits-images/soil-moisture/hover.png
assembly:
  - name: HARDWARIO Soil Sensor
  - name: HARDWARIO Core Module
  - name: HARDWARIO Sensor Module
  - name: HARDWARIO Battery Module
